### PR TITLE
fix : Complete outline Request for Unsupported Files #653

### PR DESCRIPTION
**Pull request by ap891843**
Complete outline Request for Unsupported Files #653

Signed-off-by: ap891843 <aman.prashant@broadcom.com>

### CODE REVIEW

**Comment by ap891843** [comment]
Sample output:
image

**Review by temanbrcom — APPROVED** [review]
🐰

**Comment by temanbrcom** [comment]
@asatklichov 
@grianbrcom

**Review by asatklichov — APPROVED** [review]
🏒

**Pull request merged**
