### PR TITLE
fix : allow db2 sql keywords as cobol variable name

### PR DESCRIPTION
**Pull request by ap891843**
Signed-off-by: ap891843 <aman.prashant@broadcom.com>

### CODE REVIEW

**Comment by ap891843** [comment]
22 positive tests are failing. Expected 19.

**Comment by ap891843** [comment]
[fix___allow_db2_sql_keywords_as_cobol_variable_name2.txt](https://github.com/eclipse/che-che4z-lsp-for-cobol/files/5914762/fix___allow_db2_sql_keywords_as_cobol_variable_name2.txt)

This patch should resolve all cases but needs extensive testing

**Comment by temanbrcom** [comment]
> 22 positive tests are failing. Expected 19.

I tested on the last development, it shows 22 failing tests, so it is ok

**Review by temanbrcom — APPROVED** [review]
🇬🇲

**Comment by temanbrcom** [comment]
Please, add a use case for it

**Review by grianbrcom — APPROVED** [review]
:raccoon:

**Pull request merged**
