### PR TITLE
fix: Correct coloring for CICS statements

### LINKED ISSUE #469: Support for CICS statements (basic intellisense)
As a user, I want to have a basic version of IntelliSense implemented within COBOL LSP  to improve performance and quality of work when working with a COBOL file containing CICS statements in any IDE supporting LSP.

**Acceptance Criteria:**

- [x] highlighting of CICS statements is supported (if LSP provide support for coloring)

- [x] syntax check of CICS statements is supported

- [x] fix and create unit tests for the new feature

- [x] autocomplete(content assist) of CICS statements for basic CICS keywords is supported

- [x] there is no clash with the current implementation of COBOL IntelliSense

### PR DESCRIPTION
**Pull request by grianbrcom**
Closes #469

Signed-off-by: Anton Grigorev <anton.grigorev@broadcom.com>

### CODE REVIEW

**Review by temanbrcom — APPROVED** [review]
🎨

**Comment by temanbrcom** [comment]
BTW, it doesn't really close the #469

**Review by asatklichov — APPROVED** [review]
🖌️

**Review by zacanbrcom — APPROVED** [review]
👨‍🎨 🎨

**Comment by grianbrcom** [comment]
@temanbrcom you are right. It is not close entire #469, but related to it. Maybe you need to change the description. I plan to merge it into `CICS-syntax` branch and the issue will be closed when we merge the branch.

**Comment by temanbrcom** [comment]
> @temanbrcom you are right. It is not close entire #469, but related to it. Maybe you need to change the description. I plan to merge it into `CICS-syntax` branch and the issue will be closed when we merge the branch.

Ok, sounds reasonable. I'll prepare the branch and merge this PR

**Pull request merged**
