### PR TITLE
Client snippets

### PR DESCRIPTION
**Pull request by niharikasw91**

### CODE REVIEW

**Comment by VitGottwald** [comment]
Looks good. Especially the suggestion of statements containing spaces like `RETURN ERROR`, `COPY IDMS ...`. Thank you!

**Comment by VitGottwald** [comment]
One thing is confusing though. If I specify `"cobol-lsp.dialects": ["DaCo"]` I am also getting IDMS  suggestions. At the moment the user has to specify both dialects `""cobol-lsp.dialects": ["DaCo", "IDMS"]` so we should not hard code the fact that DaCo implies IDMS and if user specified only DaCo, the should not get IDMS suggestions.

**Comment by VitGottwald** [comment]
It also looks like this branch now contains native build switch branch code. I guess we should first review and merge the native build switch and merge it. Then it will be easier to review this PR.

**Comment by niharikasw91** [comment]
> One thing is confusing though. If I specify `"cobol-lsp.dialects": ["DaCo"]` I am also getting IDMS suggestions. At the moment the user has to specify both dialects `""cobol-lsp.dialects": ["DaCo", "IDMS"]` so we should not hard code the fact that DaCo implies IDMS and if user specified only DaCo, the should not get IDMS suggestions.

I will update it.

**Review by ap891843 — APPROVED** [review]

**Review by ishche — APPROVED** [review]

**Pull request merged**
