### PR TITLE
feat: Process IDMS Records

### PR DESCRIPTION
**Pull request by Nurkambay**

### CODE REVIEW

**Review by ishche — APPROVED** [review]
LGTM :)

**Comment by VitGottwald** [comment]
@Nurkambay please, convert this to draft. Does not work on internal code samples. Will message you on separate channel.

**Comment by Nurkambay** [comment]
> @Nurkambay please, convert this to draft. Does not work on internal code samples. Will message you on separate channel.

Fixed

**Comment by VitGottwald** [comment]
LGTM. Thank you @Nurkambay !

**Review by ap891843 — APPROVED** [review]
LGTM !

**Pull request merged**
