### PR TITLE
Fix: change daco data copybook name only on first level

### PR DESCRIPTION
**Pull request by ishche**

### CODE REVIEW

**Comment by VitGottwald** [comment]
Thank you @ishche . Works well in simple cases where COPY MAID is directly bellow a containing (lower level) field. But it fails in his case

```cobol
010000     03 CNTR-XW6.
010100       05 FILLER                 PIC X(8)    VALUE 'CNTR-XW6'.   <-- this causes problem
010200       05 COPY MAID COPYBOOK XYZ.
```

**Comment by ishche** [comment]
> Thank you @ishche . Works well in simple cases where COPY MAID is directly bellow a containing (lower level) field. But it fails in his case
> 
> ```cobol
> 010000     03 CNTR-XW6.
> 010100       05 FILLER                 PIC X(8)    VALUE 'CNTR-XW6'.   <-- this causes problem
> 010200       05 COPY MAID COPYBOOK XYZ.
> ```

Could you please try again with the latest changes?

**Review by ap891843 — APPROVED** [review]
LGTM

**Review by niharikasw91 — APPROVED** [review]
LGTM!!!

**Pull request merged**
