### PR TITLE
refactor: wait for a language client to start on public api call

### PR DESCRIPTION
**Pull request by ishche**

### CODE REVIEW

**Review by temanbrcom — APPROVED** [review]

**Comment by temanbrcom** [comment]
This pr doesn't fix any user-visible behavior. Please, add the "refactor" prefix.

**Review by grianbrcom — APPROVED** [review]
:robot:

**Comment by ishche** [comment]
> This pr doesn't fix any user-visible behavior. Please, add the "refactor" prefix.

If by user you assume API user then it definitely does.

**Comment by temanbrcom** [comment]
> > This pr doesn't fix any user-visible behavior. Please, add the "refactor" prefix.
> 
> If by user you assume API user then it definitely does.

By "user" I mean Michelle. We use those prefixes to collect a changelog, and I don't see a reason to mention those changes there.

**Comment by ishche** [comment]
> By "user" I mean Michelle. We use those prefixes to collect a changelog, and I don't see a reason to mention those changes there.

ok

**Review by asatklichov — APPROVED** [review]
🏒

**Comment by temanbrcom** [comment]
14:49:45  Summary of all failing tests
14:49:45  FAIL src/__tests__/LanguageClientServiceTest.spec.ts
14:49:45    ● LanguageClientService positive scenario › Test LanguageClientService retrieve analysis passes
14:49:45  
14:49:45      TypeError: languageClient.onReady is not a function
14:49:45  
14:49:45  
14:49:45  
14:49:45        at LanguageClientService.<anonymous> (src/services/LanguageClientService.ts:1959:28)
14:49:45        at src/services/LanguageClientService.ts:1841:37
14:49:45        at Object.<anonymous>.__awaiter (src/services/LanguageClientService.ts:1784:10)
14:49:45        at LanguageClientService.retrieveAnalysis (src/services/LanguageClientService.ts:1950:12)
14:49:45        at src/__tests__/LanguageClientServiceTest.spec.ts:84:44
14:49:45        at src/__tests__/LanguageClientServiceTest.spec.ts:8:71
14:49:45        at Object.<anonymous>.__awaiter (src/__tests__/LanguageClientServiceTest.spec.ts:4:12)
14:49:45        at Object.<anonymous> (src/__tests__/LanguageClientServiceTest.spec.ts:79:76)

**Pull request merged**
