### PR TITLE
test: Adjust invalid definition error message

### PR DESCRIPTION
**Pull request by temanbrcom**
After #980.

@nalmabrcom please, check that it works.

### CODE REVIEW

**Review by grianbrcom — APPROVED** [review]
:cactus:

**Review by asatklichov — APPROVED** [review]
🦘

**Review by nalmabrcom — APPROVED** [review]
LGTM! 
Congrats on your first PR into the UI test suite 🎉

**Comment by temanbrcom** [comment]
> LGTM!
> Congrats on your first PR into the UI test suite 🎉

🍾

**Pull request merged**
