### PR TITLE
feat: make it run for Java 8

### PR DESCRIPTION
**Pull request by grianbrcom**

### CODE REVIEW

**Comment by grianbrcom** [comment]
@ap891843, take a look, please.

**Review by temanbrcom — APPROVED** [review]
🎱

**Review by ap891843 — APPROVED** [review]

**Comment by grianbrcom** [comment]
Let's merge #720 first. Because it's not Java 8 compatible. Then I can rebase this.

**Comment by grianbrcom** [comment]
image
Integration tests are not so good. Investigating...

**Review by asatklichov — APPROVED** [review]
🏯

**Pull request merged**
