### PR TITLE
Delete robot integration tests

### PR DESCRIPTION
**Pull request by grianbrcom**
This PR must be tested in the eclipse repo before merge.

### CODE REVIEW

**Review by asatklichov — APPROVED** [review]
♻️

**Comment by temanbrcom** [comment]
@nalmabrcom

**Review by temanbrcom — APPROVED** [review]
To be merged after the release

**Comment by nalmabrcom** [comment]
`Stage "Integration testing" skipped due to when conditional` wasn't present in Jenkins's job. 
Are there any other ways to test it? 
Also @grianbrcom thanks for this PR, I was going to do this in a while :D

**Comment by grianbrcom** [comment]
I'm not sure that I get you right @nalmabrcom.
Current PR was built with "development" version of Jenkinsfile. Thanks to Andrei, we have ["delTest"](https://github.com/eclipse/che-che4z-lsp-for-cobol/tree/delTest) branch in eclipse repo, you can see the build result [here](https://ci.eclipse.org/che4z/job/LSP%20for%20COBOL/job/delTest/).
I helped this robot to merge, so that's me who deleting it now.

**Comment by nalmabrcom** [comment]
@grianbrcom yes I opened this PR [build](https://ci.eclipse.org/che4z/job/LSP%20for%20COBOL/job/delTest/1/consolerl).

> I helped this robot to merge, so that's me who deleting it now.

Anyway, thanks for this PR.

**Pull request merged**
