### PR TITLE
test: Increase timeout for UI tests on CI

### PR DESCRIPTION
**Pull request by nalmabrcom**

### CODE REVIEW

**Review by asatklichov — APPROVED** [review]
🅾️

**Comment by nalmabrcom** [comment]
> 🅾️ I guess, there are some limitations kubernete's related config for lsp, please consult with Anton.

Yes, from the Jenkinsfile we can see the resources for Theia. But we are very limited with it, unfortunately. 
```
resources:
      limits:
        memory: "2Gi"
        cpu: "800m"
      requests:
        memory: "2Gi"
        cpu: "800m"
```

**Comment by temanbrcom** [comment]
Please, update the commit message to match the requirements - "test: Increase timeout for UI tests on CI"

**Review by temanbrcom — APPROVED** [review]
🧙

**Pull request merged**
