### PR TITLE
Add the context shutdown to avoid shared state on tests #199

### PR DESCRIPTION
**Pull request by temanbrcom**

### CODE REVIEW

**Comment by temanbrcom** [comment]
It is not needed for this class due to we do not load the DI context for the test, but it is loaded while verifying the logic. 
Also, it is a bad practice to use dependency injection in tests, so I'm planning to replace the Guice context calls with direct injections once we finalize it for the language engine.

**Comment by zacanbrcom** [comment]
> It is not needed for this class due to we do not load the DI context for the test, but it is loaded while verifying the logic.
> Also, it is a bad practice to use dependency injection in tests, so I'm planning to replace the Guice context calls with direct injections once we finalize it for the language engine.

I agree about to don't use the DI - I am just saying that there is already a ```shutdown``` method in the ```ConfigurableTest``` and that class could be used as place for not related unit test routine, as the shutdown.

**Comment by temanbrcom** [comment]
The problem here is that we also have the `setUp()` method in the `ConfigurableTest` marked with `@Before`. It will turn on the Guice context before each test run, but we need to avoid it, due to we check the context startup itself.

**Pull request merged**
