### PR TITLE
New updates on Copybooks

### PR DESCRIPTION
**Pull request by zeibura**
Added:
- Copybooks now downloaded manually
- Copybook autocomplete feature

### CODE REVIEW

**Comment by zeibura** [comment]
If it is any more complicated than just opening a program and the copybooks downloading, we need to write this as a procedure. If I'm understanding this right, it would be:

1. Ensure that you have a Zowe CLI zosmf profile configured
2. Choose your profile from a drop-down list, or specify it manually in settings.json (which is where, btw?)
3. "provide on or more datasets where to search for copybooks. The order of provided datasets is important." - this instruction needs clarifying, a lot. Where does the user "provide" the data sets and in what way is the order of provided data sets important?
4. Open a program and the copybooks (from the data sets provided in step 3?) download automatically.

**Comment by zimlu02** [comment]
> If it is any more complicated than just opening a program and the copybooks downloading, we need to write this as a procedure. If I'm understanding this right, it would be:
> 
> 1. Ensure that you have a Zowe CLI zosmf profile configured
> 2. Choose your profile from a drop-down list, or specify it manually in settings.json (which is where, btw?)
> 3. "provide on or more datasets where to search for copybooks. The order of provided datasets is important." - this instruction needs clarifying, a lot. Where does the user "provide" the data sets and in what way is the order of provided data sets important?
> 4. Open a program and the copybooks (from the data sets provided in step 3?) download automatically.

This description looks good to me. Some details may change though as we still finalize the work. Please ask the team for settings location.

**Comment by zeibura** [comment]
OK, I still need answers to these two questions about step 3 though.

"provide one or more data sets where to search for copybooks" - HOW?
"the order of provided data sets is important" - WHY?

Thanks.

**Comment by zacanbrcom** [comment]
> Please ask the team for settings location.

Since we support two IDEs that have slightly different concept of settings (for instance che called it preferences) and even if practically the refers both to a file with .json extension  I will suggest to say something more abstract like:

>**"Choose your profile from a drop-down list, or specify it manually in the settings section provided  by the IDE".**


The user will be able to go on the settings file and change the profile there. Moreover we can mention that we provide content suggestion inside the settings to help the user to identify the correct keys to define there.

**Comment by zacanbrcom** [comment]
> "provide one or more data sets where to search for copybooks" - HOW?
Using the "form" visible from the settings or adding manually into the json respecting the json format

> "the order of provided data sets is important" - WHY?
Because of naming collision, if you have the same member name in two different dataset defined there the download start from the first dataset defined in the list

**Comment by zeibura** [comment]
OK, the copybooks section has been updated, please have a look

**Pull request merged**
