### PR TITLE
Syntax fix in package.json

### PR DESCRIPTION
**Pull request by GaloisGirl**
Hopefully this fixes issue #1040

### CODE REVIEW

**Review by temanbrcom — APPROVED** [review]
Cool! Seems working fine. Thank you!

**Comment by temanbrcom** [comment]
@Nurkambay please, take a look at it. I will merge once you approve.

**Comment by Nurkambay** [comment]
> @Nurkambay please, take a look at it. I will merge once you approve.

This is definitely a good fix and needs to be merged, but it will not fix #1040.

**Comment by temanbrcom** [comment]
@GaloisGirl please, sign off the commit

**Comment by GaloisGirl** [comment]
> 
> 
> @GaloisGirl please, sign off the commit

What do you mean?

**Comment by temanbrcom** [comment]
> > @GaloisGirl please, sign off the commit
> 
> What do you mean?

You just need to add a "Signed-of by..." signature. The easiest way to do is running those two commands:

`git commit --amend --signoff`
`git push -f`

**Review by grianbrcom — APPROVED** [review]
:postal_horn:

**Pull request merged**
