### PR TITLE
feat: Add support for IDMS DML commands #704

### PR DESCRIPTION
**Pull request by mpicchioni**
Signed-off-by: Michael Picchioni <michael.picchioni@broadcom.com>

### CODE REVIEW

**Review by temanbrcom — APPROVED** [review]
🍨

**Review by asatklichov — APPROVED** [review]
Also apply Coloring-plugin by Anton, to keep coloring synchronized

**Review by grianbrcom — APPROVED** [review]
:maple_leaf:

**Comment by temanbrcom** [comment]
We don't have an instruction on how to use the coloring plugin, so it would be easier to do it ourselves

**Pull request merged**
