### PR TITLE
fix : fix comment mismatch bewteen pre-processor and cobol-engine.

### PR DESCRIPTION
**Pull request by ap891843**
Signed-off-by: ap891843 <aman.prashant@broadcom.com>

### CODE REVIEW

**Comment by temanbrcom** [comment]
Is it related to #601?

**Review by temanbrcom — APPROVED** [review]
🦺

**Comment by ap891843** [comment]
> Is it related to #601?

Yes.

**Review by grianbrcom — APPROVED** [review]
:robot:

**Pull request merged**
