### PR TITLE
Daco DML write report statement

### PR DESCRIPTION
**Pull request by sachin-shitole-paccar**
Added DaCO DML Write Report Statements to Parser  and Unit Tests.

### CODE REVIEW

**Review by grianbrcom — APPROVED** [review]
:raccoon:

**Comment by sachin-shitole-paccar** [comment]
@grianbrcom @temanbrcom Build pipeline is taking too much time. Is it because of my code or build server?

**Comment by temanbrcom** [comment]
Seems the target should be not `development` but the `sachin-shitole-paccar:dml-transaction-handling` branch

**Comment by sachin-shitole-paccar** [comment]
> Seems the target should be not `development` but the `sachin-shitole-paccar:dml-transaction-handling` branch

Hmm. Confused !!. My code should get merged with development branch. Correct?

**Comment by grianbrcom** [comment]
Looks like we have issues in the CI/CD pipeline. It's not related to your code.

**Comment by temanbrcom** [comment]
> > Seems the target should be not `development` but the `sachin-shitole-paccar:dml-transaction-handling` branch
> 
> Hmm. Confused !!. My code should get merged with development branch. Correct?

That's correct, the final goal is to merge all the changes to the development, but you still have a pending branch, and it should accumulate all the changes, or else we will see the same changes in the different branches. I would recommend starting the new activities from the `dml-transaction-handling` branch and opening all the prs against this, in this case, we will see only the newly added code there.

**Comment by sachin-shitole-paccar** [comment]
> > > Seems the target should be not `development` but the `sachin-shitole-paccar:dml-transaction-handling` branch
> > 
> > 
> > Hmm. Confused !!. My code should get merged with development branch. Correct?
> 
> That's correct, the final goal is to merge all the changes to the development, but you still have a pending branch, and it should accumulate all the changes, or else we will see the same changes in the different branches. I would recommend starting the new activities from the `dml-transaction-handling` branch and opening all the prs against this, in this case, we will see only the newly added code there.

You are right but then in this case I will need to keep both branches upto date with Development. Correct?
Should I cancel this PR and create new one targeting dml-transaction-branch?

**Comment by grianbrcom** [comment]
You don't need to keep both branches updated, just `dml-transaction-handling`.
The workflow can be the following:
- update dml-transaction-handling 
- create a new feature branch from dml-transaction-handling
- do implementation in the feature branch and open a PR from the feature branch to  dml-transaction-handling
- update dml-transaction-handling after merge (or any other time)
It's not needed to close this PR and open another. You can edit this PR and change the target branch.

**Comment by sachin-shitole-paccar** [comment]
@grianbrcom Not able to change target branch to "dml-transaction-handling". Actually when I try to edit it, its not showing "dml-transaction handling" branch for target.
image

**Comment by grianbrcom** [comment]
Oh, I see. Sorry, I thought that you can also change the fork name.
But it is pointless to make a PR to your fork. 

Let's do that: I will create here a branch "dml-transaction-handling" (you can choose the other name). And you will use it for your PRs. Unfortunately, you can update it only via PRs too, so you will not have control over that "dml-transaction-handling" branch.

The thing is that you must open PRs to that eclipse repo. Otherwise, it does not trigger our CI/CD pipeline.

**Comment by sachin-shitole-paccar** [comment]
@grianbrcom Ohhk got your point. No problem. Please create branch with name "daco-statements".  Then I will change PRs target branch.

**Comment by grianbrcom** [comment]
I'll wait until tests passed for #1135 and merge #1135. After that this PR will show diff only for the latest changes.

**Comment by grianbrcom** [comment]
@sachin-shitole-paccar, I squashed commits for PR #1135 in order to have a clean history. Unfortunately, this caused merge conflicts here. Can you resolve them, please?

**Comment by sachin-shitole-paccar** [comment]
> @sachin-shitole-paccar, I squashed commits for PR #1135 in order to have a clean history. Unfortunately, this caused merge conflicts here. Can you resolve them, please?

Sure will do. Thanks

**Comment by sachin-shitole-paccar** [comment]
@grianbrcom @temanbrcom I have resolve merge conflicts. Please have a look at PR.

**Review by grianbrcom — APPROVED** [review]

**Comment by sachin-shitole-paccar** [comment]
@temanbrcom @grianbrcom Could you please merge the PR if there are no corrections and suggestions? I want to start working on next set of statements.

**Comment by grianbrcom** [comment]
Oops, sorry, I was distracted.

**Pull request merged**
