### PR TITLE
fix: Allow CICS to be a variable name #597

### PR DESCRIPTION
**Pull request by ap891843**
fix: Allow CICS to be a variable name #597

### CODE REVIEW

**Comment by temanbrcom** [comment]
Please, create a use-case test for it

**Comment by ap891843** [comment]
> Please, create a use-case test for it

Done

**Review by temanbrcom — APPROVED** [review]
🚈

**Comment by temanbrcom** [comment]
@grianbrcom 
@asatklichov 
@Nurkambay

**Review by asatklichov — APPROVED** [review]
🏭

**Pull request merged**
