### PR TITLE
fix : COUNT As A Variable Name Produces Syntax Error #646

### PR DESCRIPTION
**Pull request by ap891843**
Support COUNT As A Variable Name.

Signed-off-by: ap891843 <aman.prashant@broadcom.com>

### CODE REVIEW

**Review by temanbrcom — COMMENTED** [review]
The commit message should contain a verb after the tag, something like `fix: Support COUNT as a variable name #646`

**Comment by temanbrcom** [comment]
@asatklichov 
@grianbrcom

**Review by asatklichov — APPROVED** [review]
🈂️

**Review by temanbrcom — APPROVED** [review]
☕

**Pull request merged**
