### PR TITLE
fix: Add color to hover message

### PR DESCRIPTION
**Pull request by grianbrcom**
For some reason, the coloring didn't work if I specify "COBOL" as language.

### CODE REVIEW

**Comment by grianbrcom** [comment]
I need someone to manually test it. Please take the built vsix package, install it and check the coloring.

**Review by temanbrcom — APPROVED** [review]
🕋

**Comment by nalmabrcom** [comment]
> I need someone to manually test it. Please take the built vsix package, install it and check the coloring.

I will test it ;)

**Review by nalmabrcom — APPROVED** [review]
Tested on VSC + Theia, LGTM 🎉

**Pull request merged**
