### PR TITLE
fix: replacement work if replacing or replaced text contains BY

### PR DESCRIPTION
**Pull request by ap891843**
Signed-off-by: ap891843 <aman.prashant@broadcom.com>

### CODE REVIEW

**Review by temanbrcom — APPROVED** [review]
🌾

**Comment by temanbrcom** [comment]
Please, change the commit message to "fix: Fix replacement when replacing or replaced text contains BY #900" to match the requirements

**Comment by ap891843** [comment]
> Please, change the commit message to "fix: Fix replacement when replacing or replaced text contains BY #900" to match the requirements

Done.

**Review by asatklichov — APPROVED** [review]
👍

**Pull request merged**
